server:
  port: 5001


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/predictable?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
 #  mail:
 #    host: smtp.gmail.com
 #    port: 587
 #    username:
 #    password:
 #    properties.mail.smtp:
 #            starttls.enable: true
 #            starttls.required: true
 #            auth: true



# ===============================
# = JPA / HIBERNATE
# ===============================

# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager).
# Show or not log for each sql query
  jpa:
    show-sql: true
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: update
# Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#        jdbc:
#          time_zone: UTC

security:
  user:
    password: password
  ignored:
  - "*.bundle.*"
logging:
  level:
    org.springframework.security: DEBUG
